### PR TITLE
Modified version of Ieshia's solution

### PR DESCRIPTION
**Pull request by lschiesser**
I just had to do minor changes to the algorithm so that it works.
Please look at the code again, maybe execute it to make sure that everything works.
This time I need all 3 of you to review and approve the changes, only then the two branches can be merged.

### CODE REVIEW

**Comment by lschiesser** [comment]
I also modified gui_qt.py so that it says now Random Restart Hill Climbing instead of Parallel Hill Climbing

**Review by Berit19 — APPROVED** [review]
I ran everything - works really good !! 
Before we hand it in we should delete the print lines for orders in local beam...they only appear in the cmd but are not needed ^^

**Comment by lschiesser** [comment]
> I ran everything - works really good !!
> Before we hand it in we should delete the print lines for orders in local beam...they only appear in the cmd but are not needed ^^

Yes, I already created an issue concerning this

**Review by Berit19 — APPROVED** [review]
top

**Pull request merged**
