### PR TITLE
New approach functionality

### PR DESCRIPTION
**Pull request by lschiesser**
Please leave a comment down below if you are not ok with how I realized the search strategy and result display.
You are all reviewers so (as I understood it) you all have to agree to this pull request only then the two branches are merged and changes made in new-approach-functionality will be applied to functionality-changes.
If you have any issues you can request changes via a tool

### CODE REVIEW

**Comment by Berit19** [comment]
Okay I looked at it and adjusted my code so I am okay with the changes....
There are a few things that I would still change e.g. leave out some print lines 
Only one issue: the programm stops after performing one search algorithm...we still have to fix that

**Review by Berit19 — APPROVED** [review]
Generally I approve but would make some minor changes later

**Comment by lschiesser** [comment]
> Okay I looked at it and adjusted my code so I am okay with the changes....
> There are a few things that I would still change e.g. leave out some print lines
> Only one issue: the programm stops after performing one search algorithm...we still have to fix that

For me, the program still works after performing one search algorithm. You just have to click Ok on the result window and then you can readjust your input.
The print lines are only control structures while coding to be sure that all works, we will remove them before uploading them.

**Comment by lschiesser** [comment]
> > Okay I looked at it and adjusted my code so I am okay with the changes....
> > There are a few things that I would still change e.g. leave out some print lines
> > Only one issue: the programm stops after performing one search algorithm...we still have to fix that
> 
> For me, the program still works after performing one search algorithm. You just have to click Ok on the result window and then you can readjust your input.
> The print lines are only control structures while coding to be sure that all works, we will remove them before uploading them.

Now it should work. I have two different versions on my computer and I forgot to upload the version with the return statement to GitHub, so it could not return the orderPSUs and therefore the result window could not be opened

**Review by Berit19 — APPROVED** [review]

**Review by SarahJaehnichen — APPROVED** [review]

**Pull request merged**
